[package]
name = "blenvy_demo"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { workspace = true, default-features = true,features = ["dynamic_linking"] }
blenvy.workspace = true
rand.workspace = true
avian3d.workspace = true